[build]
command = "bundle exec jekyll build --config '_config.yml,_config_staging.yml'"
publish = "_site"

[build.environment]
RUBY_VERSION = "3.4.8"

[[redirects]]
  from = "/"
  to = "/planning/statements/"

[dev]
publish = "_site"
framework = "#static"

